services:
  - type: web
    name: render-post-deploy
    env: python
    buildCommand: poetry install
    startCommand: gunicorn app:app --chdir ./render_post_deploy
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
