services:
  - type: web
    name: render-post-deploy
    env: python
    buildCommand: |
      poetry lock --no-update && poetry install
    startCommand: hypercorn render_post_deploy.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
