services:
  - type: web
    name: render-post-deploy
    env: python
    buildCommand: |
      export POETRY_HOME="$(pwd)/.poetry" \
      && curl -sSL https://install.python-poetry.org | python3 - \
      && export PATH="$POETRY_HOME/bin:$PATH" \
      && poetry --version
    startCommand: hypercorn render_post_deploy.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
