name: deploy

on:
  push

jobs:
  check_deploy_integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: wait for deploy to complete
        run: curl --head --retry 600 --retry-all-errors --fail --retry-delay 1 "${CHECK_HOSTNAME}/version-check/${GITHUB_SHA}"
        # run: npx wait-on --timeout 600000 "${CHECK_HOSTNAME}/version-check/${GITHUB_SHA}"
        env:
          CHECK_HOSTNAME: https://render-post-deploy.onrender.com
      - run: echo App deployed!!
